title: Stack Problems
description: My Personal Stack Problems
author: Roc
tagline: SE DevOps
github: github.com/sunnyroc
about: I am a dev-ops. Currently doing more in backend and focused in <code>Java</code>.
disqus_shortname: #stackproblems
google_analytics: #UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg
skilled: [HTML5 & CSS, Python & Django, PHP & Laravel,Node & Vue]
enableTags: true
tagarray: []
style: styles-2
email: bien.sun@hotmail.com
phone: 13052739901
website: sunnyroc.github.io
linkedin: sun-roc-7517a496

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    # - icon: fa-facebook
    #   link: "#"
    # - icon: fa-qq
    #   link: "356179"
    # - icon: fa-twitter
      # link: #"https://twitter.com/agusmakmun6"
    - icon: fa-linkedin
      link: https://in.linkedin.com/in/sun-roc-7517a496
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/sunnyroc"

share:
  twitter_username: #agusmakmun6
  fb_appid: #1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Resume
      url: /resume_en/
    # - text: My Projects
    #   url: /projects/
    - text: XML Feed
      url: /feed.xml


url: "https://sunnyroc.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
